apiVersion: v1
kind: Service
metadata:
  name: service-history
spec:
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30009
      protocol: TCP
  type: NodePort
  selector:
    name: label-history
