apiVersion: v1
kind: Service
metadata:
  name: historyservice
spec:
  ports:
    - port: 8083
      targetPort: 8080
      #nodePort: 30003
      protocol: TCP
  type: LoadBalancer
  selector:
    name: history-label
